apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace}}
data:
  IMAGE_NAME: "{{ .Values.configMap.IMAGE_NAME }}"
  MOUNT_DEST: "{{ .Values.configMap.MOUNT_DEST }}"