apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  serviceName: {{ .Chart.Name }}-driver
  selector:
    matchLabels:
      {{ include "lsdisk.labels" . | indent 6 }}
      component: controller
  template:
    metadata:
      labels:
        {{ include "lsdisk.labels" . | indent 8 }}
        component: controller
    spec:
      serviceAccountName: {{ .Chart.Name }}-driver
      priorityClassName: system-cluster-critical
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: Equal
          value: "true"
          effect: NoSchedule
      volumes:
        - name: socket-dir
          emptyDir: {}
      containers:
        - name: csi-driver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_IMAGE
              value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            - name: TZ
              value: {{ .Values.timezone | quote }}
            - name: PROVISIONER_NAME
              value: {{ .Values.provisionerName | quote }}
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          envFrom:
            - configMapRef:
                name: lsdisk
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          ports:
            - name: csi-probe
              containerPort: 9808
        - name: external-resizer
          image: {{ .Values.resizerImage }}
          imagePullPolicy: IfNotPresent
          args:
            - "--csi-address=$(ADDRESS)"
            - "--handle-volume-inuse-error=false"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi