apiVersion: v1
kind: Service
metadata:
  name: lsdisk-controller
  labels:
    app.kubernetes.io/instance: lsdisk
    app.kubernetes.io/name: lsdisk
    component: controller
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: lsdisk
    app.kubernetes.io/name: lsdisk
    component: controller
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lsdisk-controller
spec:
  replicas: 1
  serviceName: lsdisk-driver
  selector:
    matchLabels: 
      app.kubernetes.io/instance: lsdisk
      app.kubernetes.io/name: lsdisk
      component: controller
  template:
    metadata:
      labels: 
        app.kubernetes.io/instance: lsdisk
        app.kubernetes.io/name: lsdisk
        component: controller
    spec:
      serviceAccount: lsdisk-driver
      priorityClassName: system-cluster-critical
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: Equal
          value: "true"
          effect: NoSchedule
      volumes:
        - name: socket-dir
          emptyDir: {}
      containers:
        - name: csi-driver
          image: danialnabiyan1382/lsdisk:v1.0.0.47
          imagePullPolicy: IfNotPresent
          env:
            - name: PROVISIONER_NAME
              value: "lsdisk.driver"
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          ports:
            - name: csi-probe
              containerPort: 9808
          resources:
            limits:
              cpu: "1"
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
        - name: external-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.13.1
          imagePullPolicy: IfNotPresent
          args:
            - "--csi-address=$(ADDRESS)"
            - "--handle-volume-inuse-error=false"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
