image:
  repository: danialnabiyan1382/lsdisk
  tag: v2.0.3
  pullPolicy: IfNotPresent
resizerImage: registry.k8s.io/sig-storage/csi-resizer:v1.9.0
registrarImage: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.12.0
provisionerImage: registry.k8s.io/sig-storage/csi-provisioner:v5.0.2
timezone: Asia/Tehran
configMap:
  IMAGE_NAME: "disk.img"
  MOUNT_DEST: "/mnt"
resources:
  limits:
    cpu: "1"
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 100Mi